package com.hitsproject.photoeditor

enum class RequestCode {
    IMAGE_PICK,
    IMAGE_CAPTURE,
    CAMERA_PERMISSION,
    IMAGE_PERMISSION,
    MANAGE_STORAGE_PERMISSION,
    WRITE_STORAGE_PERMISSION,
    REQUEST_CODE_SAVE_IMAGE
}